[package]
name = "platscope-pricing"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
platscope-domain = { path = "../platscope-domain" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
